"""P1 baseline: tenant, users, customers, daily service records, ledger, audit, sync register.

Revision ID: 0001_p1_baseline
Revises:
Create Date: P1 — Backend & Data Foundation

Written by hand rather than autogenerated so every constraint named in P0 §6 is
explicit and reviewable, and so constraint names are stable for the schema
assertion test.

Contains P1 tables ONLY. billing_cycle, statement, payment, reminder,
communication_log, commission_* and job_run belong to later packages and are
deliberately absent.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_p1_baseline"
down_revision = None
branch_labels = None
depends_on = None

UUID = postgresql.UUID(as_uuid=True)
TS = sa.DateTime(timezone=True)
ROW_VERSION_DEFAULT = sa.text("nextval('row_version_seq')")


def upgrade() -> None:
    # One shared sequence across every versioned table, so row_version doubles as
    # a globally monotonic cursor for the P5 sync change feed (P0 §6, §7.4).
    op.execute("CREATE SEQUENCE row_version_seq AS BIGINT START WITH 1 INCREMENT BY 1")

    # ------------------------------------------------------------------ tenant
    op.create_table(
        "tenant",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("slug", sa.String(64), nullable=False, unique=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False, server_default="PKR"),
        sa.Column("currency_exponent", sa.SmallInteger, nullable=False, server_default="2"),
        sa.Column("unit_label", sa.String(32), nullable=False, server_default="unit"),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="Asia/Karachi"),
        sa.Column("cycle_type", sa.String(16), nullable=False, server_default="MONTHLY"),
        sa.Column("cycle_start_day", sa.SmallInteger, nullable=False, server_default="1"),
        sa.Column("reminder_schedule", postgresql.JSONB, nullable=False),
        sa.Column("default_unit_price_minor", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("default_quantity", sa.Numeric(12, 3), nullable=False, server_default="0"),
        sa.Column("status", sa.String(16), nullable=False, server_default="ACTIVE"),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("row_version", sa.BigInteger, nullable=False, server_default=ROW_VERSION_DEFAULT),
        sa.CheckConstraint("currency_exponent BETWEEN 0 AND 4", name="currency_exponent_range"),
        sa.CheckConstraint("default_unit_price_minor >= 0", name="default_price_non_negative"),
        sa.CheckConstraint("default_quantity >= 0", name="default_quantity_non_negative"),
        sa.CheckConstraint("cycle_start_day BETWEEN 1 AND 28", name="cycle_start_day_range"),
        sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED')", name="status_valid"),
    )

    # ---------------------------------------------------------------- app_user
    op.create_table(
        "app_user",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="ACTIVE"),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("tenant_id", "id", name="uq_app_user_tenant_id_id"),
        sa.CheckConstraint(
            "role IN ('OWNER_ADMIN','PLATFORM_OWNER','OPERATOR')", name="role_valid"
        ),
        sa.CheckConstraint("status IN ('ACTIVE','DISABLED')", name="status_valid"),
        # SEC-6, structurally: tenant-scoped or platform-scoped, never both.
        sa.CheckConstraint(
            "(role = 'PLATFORM_OWNER' AND tenant_id IS NULL) "
            "OR (role <> 'PLATFORM_OWNER' AND tenant_id IS NOT NULL)",
            name="scope_matches_role",
        ),
    )
    op.create_index(
        "uq_app_user_tenant_email",
        "app_user",
        ["tenant_id", sa.text("lower(email)")],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )
    op.create_index(
        "uq_app_user_platform_email",
        "app_user",
        [sa.text("lower(email)")],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NULL"),
    )

    # ------------------------------------------------------------ user_session
    op.create_table(
        "user_session",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=True),
        sa.Column("user_id", UUID, sa.ForeignKey("app_user.id"), nullable=False),
        sa.Column("refresh_token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("issued_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("expires_at", TS, nullable=False),
        sa.Column("revoked_at", TS, nullable=True),
        sa.Column("device_label", sa.String(120), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["app_user.tenant_id", "app_user.id"],
            name="fk_user_session_tenant_id_user_id",
        ),
    )

    # ---------------------------------------------------------------- customer
    op.create_table(
        "customer",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("phone_e164", sa.String(20), nullable=True),
        sa.Column("whatsapp_e164", sa.String(20), nullable=True),
        sa.Column("address", sa.Text, nullable=True),
        sa.Column("area", sa.String(120), nullable=True),
        sa.Column("default_quantity", sa.Numeric(12, 3), nullable=False, server_default="0"),
        sa.Column("unit_price_minor", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("status", sa.String(16), nullable=False, server_default="ACTIVE"),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("row_version", sa.BigInteger, nullable=False, server_default=ROW_VERSION_DEFAULT),
        # SEC-2: composite-FK target.
        sa.UniqueConstraint("tenant_id", "id", name="uq_customer_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_customer_tenant_id_code"),
        sa.CheckConstraint("default_quantity >= 0", name="default_quantity_non_negative"),
        sa.CheckConstraint("unit_price_minor >= 0", name="unit_price_non_negative"),
        sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name="status_valid"),
        sa.CheckConstraint("length(btrim(name)) > 0", name="name_not_blank"),
        sa.CheckConstraint("length(btrim(code)) > 0", name="code_not_blank"),
    )
    op.create_index("ix_customer_tenant_id_area", "customer", ["tenant_id", "area"])
    op.create_index("ix_customer_tenant_id_name", "customer", ["tenant_id", "name"])

    # ---------------------------------------------------- daily_service_record
    op.create_table(
        "daily_service_record",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("customer_id", UUID, nullable=False),
        sa.Column("service_date", sa.Date, nullable=False),
        sa.Column("quantity", sa.Numeric(12, 3), nullable=False),
        sa.Column("unit_price_minor", sa.BigInteger, nullable=False),
        sa.Column("unit_label", sa.String(32), nullable=False),
        sa.Column("charge_minor", sa.BigInteger, nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="ACTIVE"),
        sa.Column("corrects_id", UUID, nullable=True),
        sa.Column("superseded_by_id", UUID, nullable=True),
        sa.Column("adjustment_minor", sa.BigInteger, nullable=True),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("recorded_by_user_id", UUID, sa.ForeignKey("app_user.id"), nullable=False),
        sa.Column("operation_id", UUID, nullable=False),
        sa.Column("source", sa.String(16), nullable=False, server_default="ONLINE"),
        sa.Column("input_method", sa.String(16), nullable=False, server_default="BUTTON"),
        sa.Column("recorded_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("row_version", sa.BigInteger, nullable=False, server_default=ROW_VERSION_DEFAULT),
        sa.UniqueConstraint("tenant_id", "id", name="uq_daily_service_record_tenant_id_id"),
        # SEC-2: a record can never point at another tenant's customer.
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customer.tenant_id", "customer.id"],
            name="fk_daily_service_record_tenant_id_customer_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "corrects_id"],
            ["daily_service_record.tenant_id", "daily_service_record.id"],
            name="fk_daily_service_record_tenant_id_corrects_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "superseded_by_id"],
            ["daily_service_record.tenant_id", "daily_service_record.id"],
            name="fk_daily_service_record_tenant_id_superseded_by_id",
        ),
        sa.CheckConstraint("quantity >= 0", name="quantity_non_negative"),
        sa.CheckConstraint("unit_price_minor >= 0", name="unit_price_non_negative"),
        sa.CheckConstraint("charge_minor >= 0", name="charge_non_negative"),
        sa.CheckConstraint("kind IN ('SERVICE','SKIP')", name="kind_valid"),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUPERSEDED','VOIDED')", name="status_valid"
        ),
        sa.CheckConstraint(
            "source IN ('ONLINE','SYNC','IMPORT')", name="source_valid"
        ),
        sa.CheckConstraint(
            "input_method IN ('BUTTON','VOICE')", name="input_method_valid"
        ),
        # FIN-7 enforced by the database, not only by application code.
        sa.CheckConstraint(
            "kind <> 'SKIP' OR (quantity = 0 AND charge_minor = 0)",
            name="skip_is_zero",
        ),
    )
    # SYN-4: THE duplicate-service guarantee. Partial, so superseded/voided rows
    # may share a (customer, date) while exactly one ACTIVE row can exist.
    op.create_index(
        "uq_daily_service_record_active_day",
        "daily_service_record",
        ["tenant_id", "customer_id", "service_date"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        "ix_daily_service_record_tenant_id_customer_id_service_date",
        "daily_service_record",
        ["tenant_id", "customer_id", "service_date"],
    )

    # ------------------------------------------------------------ ledger_entry
    op.create_table(
        "ledger_entry",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("customer_id", UUID, nullable=False),
        sa.Column("entry_kind", sa.String(16), nullable=False),
        sa.Column("amount_minor", sa.BigInteger, nullable=False),
        sa.Column("occurred_on", sa.Date, nullable=False),
        # No FK yet: billing_cycle is a P2 table. P2 adds the FK and the posting
        # rule (P0 §5.5) without changing this table's shape.
        sa.Column("posting_cycle_id", UUID, nullable=True),
        sa.Column("source_type", sa.String(32), nullable=False),
        sa.Column("source_id", UUID, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("created_by_user_id", UUID, sa.ForeignKey("app_user.id"), nullable=True),
        sa.Column("row_version", sa.BigInteger, nullable=False, server_default=ROW_VERSION_DEFAULT),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customer.tenant_id", "customer.id"],
            name="fk_ledger_entry_tenant_id_customer_id",
        ),
        # One source document can never post the same kind of entry twice.
        sa.UniqueConstraint(
            "tenant_id",
            "source_type",
            "source_id",
            "entry_kind",
            name="uq_ledger_entry_tenant_id_source_type_source_id_entry_kind",
        ),
        sa.CheckConstraint("amount_minor <> 0", name="amount_non_zero"),
        sa.CheckConstraint(
            "entry_kind IN ('OPENING','CHARGE','PAYMENT','ADJUSTMENT')",
            name="entry_kind_valid",
        ),
    )
    op.create_index(
        "ix_ledger_entry_tenant_id_customer_id_id",
        "ledger_entry",
        ["tenant_id", "customer_id", "id"],
    )
    op.create_index(
        "ix_ledger_entry_tenant_id_posting_cycle_id",
        "ledger_entry",
        ["tenant_id", "posting_cycle_id"],
    )

    # ------------------------------------------------------------- audit_event
    op.create_table(
        "audit_event",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=True),
        sa.Column("actor_user_id", UUID, sa.ForeignKey("app_user.id"), nullable=True),
        sa.Column("actor_scope", sa.String(16), nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("entity_type", sa.String(64), nullable=False),
        sa.Column("entity_id", UUID, nullable=True),
        sa.Column("before", postgresql.JSONB, nullable=True),
        sa.Column("after", postgresql.JSONB, nullable=True),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("request_id", sa.String(64), nullable=True),
        sa.Column("operation_id", UUID, nullable=True),
        sa.Column("source", sa.String(16), nullable=False, server_default="ONLINE"),
        sa.Column("occurred_at", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "actor_scope IN ('TENANT','PLATFORM','SYSTEM')", name="actor_scope_valid"
        ),
        sa.CheckConstraint(
            "source IN ('ONLINE','SYNC','JOB','PLATFORM')", name="source_valid"
        ),
    )
    op.create_index("ix_audit_event_tenant_id_occurred_at", "audit_event", ["tenant_id", "occurred_at"])
    op.create_index(
        "ix_audit_event_tenant_id_entity_type_entity_id",
        "audit_event",
        ["tenant_id", "entity_type", "entity_id"],
    )

    # ---------------------------------------------------------- sync_operation
    op.create_table(
        "sync_operation",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("tenant_id", UUID, sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("operation_id", UUID, nullable=False),
        sa.Column("user_id", UUID, sa.ForeignKey("app_user.id"), nullable=True),
        sa.Column("op_type", sa.String(64), nullable=False),
        sa.Column("request_hash", sa.String(64), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("result", postgresql.JSONB, nullable=True),
        sa.Column("entity_type", sa.String(64), nullable=True),
        sa.Column("entity_id", UUID, nullable=True),
        sa.Column("received_at", TS, nullable=False, server_default=sa.func.now()),
        # SYN-2: the serialization point for concurrent replays.
        sa.UniqueConstraint(
            "tenant_id", "operation_id", name="uq_sync_operation_tenant_id_operation_id"
        ),
        sa.CheckConstraint(
            "status IN ('APPLIED','REJECTED','CONFLICT')", name="status_valid"
        ),
    )
    op.create_index(
        "ix_sync_operation_tenant_id_received_at", "sync_operation", ["tenant_id", "received_at"]
    )


def downgrade() -> None:
    op.drop_table("sync_operation")
    op.drop_table("audit_event")
    op.drop_table("ledger_entry")
    op.drop_table("daily_service_record")
    op.drop_table("customer")
    op.drop_table("user_session")
    op.drop_table("app_user")
    op.drop_table("tenant")
    op.execute("DROP SEQUENCE IF EXISTS row_version_seq")
